######################################################################
# Automatically generated by qmake (2.01a) Fr Jan 25 22:55:04 2008
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../src/Task.h
SOURCES += testtask.cpp ../src/Task.cpp
