######################################################################
# Automatically generated by qmake (2.01a) Mo Mrz 5 21:04:13 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Job.h JobWindow.h JobModel.h JobEdit.h JobFilter.h
FORMS += jobtimer.ui
SOURCES += main.cpp Job.cpp JobWindow.cpp JobModel.cpp JobEdit.cpp JobFilter.cpp
RESOURCES = pics.qrc
